### ISSUE TITLE
Loop in Update Station

### ISSUE THREAD

**Issue by q-pa** [ghostbsd/issues#95] opened 2024-02-17 10:00 UTC
### Version

23.10.1

### What desktop?

Official MATE

### Explain the issue and what happens

Another computer to update to 24.01.1 but this time I am running into a problem. Update station loops. I cannot tell where the problem is, because it's too quick. So I shut down the computer but then it booted to a black screen with mouse cursor. Now I booted back into the backup BE. Where can I find any update logs? What would be the next step? Upgrade GhostBSD 23.10.1 to 24.10.1 with pkg? Please advise.

### Explain how to reproduce the bug?

Tried to update from 23.10.1 to 24.01.1 with Update Station.

### What is the Expected behavior (if applicable)

Smooth update like on my other two computers.

**Comment by stefan1241** [comment] 2024-02-17 14:49
I can confirm this behavior. I just wanted to upgrade my old laptop and ran into the same issue. A never ending loop. Update-station downloads 1066 packages then it starts to extract and install them. After package 1000 the message "checking for candidates" appear and update-station begins to extract and install package no. 1 again. After 100 or 200 hundred packages it starts with package no. 1 again. I had to kill the processes to stop it.

**Comment by stefan1241** [comment] 2024-02-17 14:54
I use XFCE.

**Comment by ericbsd** [comment] 2024-02-17 18:38
It is a duplicate of https://github.com/ghostbsd/issues/issues/29.

**Closed** 2024-02-17 18:54 UTC
Labels: bug, duplicate

**Comment by q-pa** [comment] 2024-02-18 16:23
I tried again. The looping Update Station ran for 6 hrs, then I killed process pkg-static and rebooted. There were a few packages to update after the reboot plus all entries below nobody were missing in /etc/passwd. I did
`/usr/sbin/pwd_mkdb -p /etc/master.passwd` which restored /etc/passwd.
