### ISSUE TITLE
Telegram-desktop is broken

### ISSUE THREAD

**Issue by hansw-nlo** [ghostbsd/issues#39] opened 2023-11-10 17:02 UTC
### Version

23.10.1

### Explain the issue and what happens

Telegram-desktop is not working anymore. When starting it from the cli I see the following

ld-elf.so.1: /usr/local/lib/qt5/libQt5Core.so.5: Undefined symbol "_ZTVNSt3__13pmr25monotonic_buffer_resourceE"

### Explain how to reproduce the bug?

...

**Comment by ericbsd** [comment] 2023-11-10 23:27
I am looking into it. So far, I am not able to reproduce it.

**Comment by hansw-nlo** [comment] 2023-11-11 16:17
I did remove Linux support a while ago, can that be the problem? It refers to libelf I think

**Comment by hansw-nlo** [comment] 2023-11-11 19:19
I made sure the linux support is started again, does not make a difference

**Comment by ericbsd** [comment] 2023-11-11 20:21
Telegram Desktop is native. It must be related to https://github.com/ghostbsd/issues/issues/29. A bad upgrade would cause that. I am recommending that you run `sudo upgrade -r`. I use Telegram Desktop daily on my desktop and laptop, which is fine.

**Comment by hansw-nlo** [comment] 2023-11-12 09:51
sudo upgrade -f
Password:
sudo: upgrade: command not found


Is this related to the loop during an upgrade? I am a bit worried if something like this is the result.

**Comment by hansw-nlo** [comment] 2023-11-12 09:53
Ah, sudo pkg upgrade -f. I do hope this will not result in another loop

**Comment by hansw-nlo** [comment] 2023-11-12 10:20
[1331/1333] Extracting linux_base-c7-7.9.2009_1: 100%
pkg: Fail to rename /compat/linux/.pkgtemp.bin.Uped9f1MKJmt -> /compat/linux/bin:Is a directory

Something is broken....

**Comment by hansw-nlo** [comment] 2023-11-12 12:14
Ok, service disabled, upgrade done, no real errors. I still get the same message about Telegram-desktop.

I give up, I will simply plan my move to FreeBSD itself a bit sooner.

**Comment by ericbsd** [comment] 2023-11-12 14:22
Oh, `bectl list` should show it.

```bash
> bectl list
BE                       Active Mountpoint Space Created
backup-2023-11-11-23-23  -      -          146M  2023-11-11 23:23
initial                  NR     /          120G  2021-02-27 14:36
new                      -      -          44.4G 2023-05-22 15:18
upgrade-November-02-2023 -      -          163M  2023-11-02 20:50
```

**Comment by hansw-nlo** [comment] 2023-11-12 14:25
bectl list
BE                      Active Mountpoint Space Created
backup-2023-11-09-16-06 -      -          21.9G 2023-11-09 16:06
default                 NR     /          79.4G 2022-11-08 19:31

**Comment by hansw-nlo** [comment] 2023-11-12 14:42
My interpretation of this is that either QtCore5 has changed and the software might not be able to work due to it or there is something wrong with the elfutils. 

See also this:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272642

These errors are familiar with Qt errors so I suppose something changed there, dunno if that is fixed before the final 14.0 version.

**Comment by hansw-nlo** [comment] 2023-11-12 15:23
And it is confirmed, there is a patch released for 14.x

**Comment by ericbsd** [comment] 2023-11-12 17:18
Thanks for that. I was looking for something like that, but I and Google seem to have a bad relationship because it does not give anything like that.

I am unsure if it is related because I did a clean install of GhostBSD and can't reproduce it on a clean install.

**Comment by hansw-nlo** [comment] 2023-11-12 17:24
Then the real question is, are you patching Ghost or not. If not, I will not invest any time to try and make it run here. Might as well directly go to FreeBSD in that case.

I do not want to sound harsh, but IMHO the team for Ghost might be to small to handle such bugs

**Comment by hansw-nlo** [comment] 2023-11-12 17:24
I mean, even I was able to find it

**Comment by ericbsd** [comment] 2023-11-12 20:57
First, I rarely have to patch because I directly sync ghostbsd-src with the freebsd-src.

I take the issue seriously and spent time trying to reproduce this issue on two devices and a VM. I can't reproduce it.

Oh, the patch that Ed Maste did https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272642 was reverted. So, there is no patch to add to GhostBSD.

After reading the bug report, my conclusion is still the same: a bad upgrade. The reason for my conclusion is due to the problem of https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272642. If you read carefully, it was reproduced with `make installworld`, and not running `make delete-old`. It was also reproduced with `freebsd-update`, which GhostBSD does not use, and ED tried to reproduce and was unable to reproduce. When the update started to loop, the base OS packages were not appropriately cleaned and did not remove the old libs.

I will take the blame for what Update Station did with PKG.

> I mean, even I was able to find it
I was not looking for FreeBSD specifically. I was looking for what could cause QT to behave like that. I focused on reproducing the issue, not looking for issues related to this on the FreeBSD side.

I am closing this since there is nothing I can do other than fix Update Station, and there is a ticket already for this.

You are welcome to go to FreeBSD if you are unhappy with GhostBSD.

**Closed by ericbsd** 2023-11-12 20:57 UTC
Labels: bug
